include:
  - ./app/compose.yaml
  - ./docker/compose.yaml

services:
  app:
    env_file:
      - ./app/.env
    environment:
      OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      otel-collector:
        condition: service_started
