services:
  mimir:
    image: grafana/mimir:3.0.6
    restart: unless-stopped
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - mimir_data:/data/mimir
    command: ["--config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"

  tempo:
    image: grafana/tempo
    restart: unless-stopped
    user: root
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/data/tempo
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"

  loki:
    image: grafana/loki
    restart: unless-stopped
    user: root
    volumes:
      - ./loki/loki.yaml:/etc/loki.yaml
      - loki_data:/data/loki
    command: ["-config.file=/etc/loki.yaml"]
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    volumes:
      - ./otel/collector.yaml:/etc/otel-collector.yaml
      - /:/hostfs:ro
    command: ["--config=/etc/otel-collector.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - mimir
      - tempo
      - loki

  grafana:
    image: grafana/grafana:main
    restart: unless-stopped
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - mimir
      - tempo
      - loki

volumes:
  mimir_data:
  tempo_data:
  loki_data:
  grafana_data:
