---
apiVersion: batch/v1
kind: Job
metadata:
  name: movie-rating-migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migrations
        image: movie-rating-migrations:v1.0.0
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: movie-rating-db
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: movie-rating-db
                key: POSTGRES_PASSWORD
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: movie-rating-db
                key: POSTGRES_DB
          - name: DB_ADDRESS
            value: movie-rating-db
          - name: DB_PORT
            value: "5432"
        command:
        - /bin/sh
        - -c
        - |
          apk add gcc python3-dev musl-dev linux-headers
          uv sync --no-install-project --frozen &&
          uv run alembic upgrade head
      restartPolicy: Never
