local:
  enabled: true

secrets:
  jwtSecretKey: jwt-secret-key
  dbUser: movie-rating
  dbPassword: movie-rating-password
  dbDatabase: movie-rating
  dbAddress: movie-rating-postgresql
  dbPort: 5432

postgresql:
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: movie-rating
    password: movie-rating-password
    database: movie-rating
  primary:
    networkPolicy:
      enabled: false

app:
  image:
    tag: "1.0.0"
  resources:
    requests:
      cpu: 15m
      memory: 225M
      ephemeral-storage: 128Mi
    limits:
      cpu: 29m
      memory: 598M
      ephemeral-storage: 256Mi
  ingress:
    enabled: true
    className: kong
    host: movie-rating.local.com

migrations:
  image:
    tag: "1.0.0"
  resources:
    requests:
      cpu: 15m
      memory: 225M
      ephemeral-storage: 128Mi
    limits:
      cpu: 29m
      memory: 598M
      ephemeral-storage: 2Gi
