"""change name fields to unique

Revision ID: 2c97d16346e1
Revises: f8a59e4233fa
Create Date: 2026-04-20 13:58:57.343459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c97d16346e1'
down_revision: Union[str, Sequence[str], None] = 'f8a59e4233fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'actors', ['name'])
    op.create_unique_constraint(None, 'movies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'actors', type_='unique')
    # ### end Alembic commands ###
