"""add ondelete cascade into intemediate tables

Revision ID: e6bbdb39d7b2
Revises: 9315c15ffd99
Create Date: 2026-04-20 18:07:51.071586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bbdb39d7b2'
down_revision: Union[str, Sequence[str], None] = '9315c15ffd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('movies_actors_actor_id_fkey'), 'movies_actors', type_='foreignkey')
    op.drop_constraint(op.f('movies_actors_movie_id_fkey'), 'movies_actors', type_='foreignkey')
    op.create_foreign_key(None, 'movies_actors', 'actors', ['actor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movies_actors', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_movies_user_id_fkey'), 'users_movies', type_='foreignkey')
    op.drop_constraint(op.f('users_movies_movie_id_fkey'), 'users_movies', type_='foreignkey')
    op.create_foreign_key(None, 'users_movies', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_movies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_movies', type_='foreignkey')
    op.drop_constraint(None, 'users_movies', type_='foreignkey')
    op.create_foreign_key(op.f('users_movies_movie_id_fkey'), 'users_movies', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('users_movies_user_id_fkey'), 'users_movies', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'movies_actors', type_='foreignkey')
    op.drop_constraint(None, 'movies_actors', type_='foreignkey')
    op.create_foreign_key(op.f('movies_actors_movie_id_fkey'), 'movies_actors', 'movies', ['movie_id'], ['id'])
    op.create_foreign_key(op.f('movies_actors_actor_id_fkey'), 'movies_actors', 'actors', ['actor_id'], ['id'])
    # ### end Alembic commands ###
