---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{ .Chart.Name }}-api
        {{- if .Values.local.enabled }}
        imagePullPolicy: IfNotPresent
        {{- end }}
        image: {{ .Chart.Name }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: 8000
        {{- if .Values.local.enabled }}
        env: {{ include "movie-rating.app.env" . | indent 10 }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.app.resources.requests.cpu }}
            memory: {{ .Values.app.resources.requests.memory }}
            ephemeral-storage: {{ index .Values.app.resources.requests "ephemeral-storage" }}
          limits:
            cpu: {{ .Values.app.resources.limits.cpu }}
            memory: {{ .Values.app.resources.limits.memory }}
            ephemeral-storage: {{ index .Values.app.resources.limits "ephemeral-storage" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-api
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.app.ingress.className }}
  rules:
  - host: {{ .Values.app.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Chart.Name }}-api
            port:
              number: 8000
