{{- if .Values.local.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrations
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: migrations
        image: {{ .Chart.Name }}-migrations:{{ .Values.migrations.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        env: {{ include "movie-rating.migrations.env" . | indent 10 }}
        resources:
          requests:
            cpu: {{ .Values.migrations.resources.requests.cpu }}
            memory: {{ .Values.migrations.resources.requests.memory }}
            ephemeral-storage: {{ index .Values.migrations.resources.requests "ephemeral-storage" }}
          limits:
            cpu: {{ .Values.migrations.resources.limits.cpu }}
            memory: {{ .Values.migrations.resources.limits.memory }}
            ephemeral-storage: {{ index .Values.migrations.resources.limits "ephemeral-storage" }}
        command:
        - /bin/sh
        - -c
        - |
          apk add gcc python3-dev musl-dev linux-headers
          uv sync --no-install-project --frozen &&
          uv run alembic upgrade head
      restartPolicy: Never
{{- end }}
