{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey }}
  DB_USER: {{ .Values.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  DB_DATABASE: {{ .Values.secrets.dbDatabase }}
  DB_ADDRESS: {{ .Values.secrets.dbAddress }}
  DB_PORT: {{ .Values.secrets.dbPort }}
{{- end }}
